# Main settings
title: Divine Kids
email: your-email@domain.com
description: DIVINE KIDS - Game Pertama Indonesia Resmi (Officialy First Indonesian Game)
baseurl: "/www.divinekids.com" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
disqus:
  shortname: divinekids
lang: id

# Build settings
markdown: kramdown
encoding: "utf-8"
timezone: Asia/Jakarta
theme: minima
sass:
  style: compressed
gems: # see Gemfile.lock list of usable gem.
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _games/README.md
  - _comics/README.md
  - _data/README.md
  - script
permalink: /blog/:title

# Collections
collections:
  games:
    output: true
    permalink: /:collection/:name
  comics:
    output: true
    permalink: /:collection/:name

# Default values
defaults:

  # Common scopes
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
      image_path: /images/blog/

  # Collections
  - scope:
      type: games
    values:
      layout: page
      image_path: /images/gallery/
  - scope:
      type: comics
    values:
      layout: page
      image_path: /images/gallery/
